# Test 2023-05-25 at 00:26:40

name: Test

on:
  push

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Postgres
      run: |
        wget https://get.enterprisedb.com/postgresql/postgresql-15.3-1-windows-x64.exe

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Postgres
      run: |
        curl https://get.enterprisedb.com/postgresql/postgresql-15.3-1-windows-x64.exe
